### ISSUE TITLE
Getting Unexpected Error message while submitting a new license

### ISSUE THREAD

**Issue by ithompson4** [spdx/spdx-online-tools#112]
Steps to reproduce:

- Click on "Submit New License" on the navigation panel
- Fill in all required fields in the form
- Click on "Submit" button 

Actual Result:

![error1](https://user-images.githubusercontent.com/16367007/55206615-82f81800-51ad-11e9-8067-8fbcef256564.png)

![error2](https://user-images.githubusercontent.com/16367007/55206624-87bccc00-51ad-11e9-9480-106bc4f46551.png)

**Comment by techytushar** [comment]
@ithompson4 this error should not occur, can you please paste the `Standard License Header` text that you are submitting

**Comment by ithompson4** [comment]
I tried different `Standard License Header` texts, for example:

`/*` Copyright (C) Iryna's Systems, Inc - All Rights Reserved
 `*` Unauthorized copying of this file, via any medium is strictly prohibited
 `*` Proprietary and confidential
 `*` Written by Iryna <test123@gmail.com>, May 2018
 `*/`

But this field is not required. When I leave `Standard License Header` field empty, I get the same error. Where can I get the valid data for required fields to test this flow? Thanks.

**Comment by Ugtan** [comment]
> But this field is not required. When I leave `Standard License Header` field empty, I get the same error

It is working fine for me. Can you share all the input fields you have entered in the form while you are getting this error.


> Where can I get the valid data for required fields to test this flow? Thanks.

[Here](https://spdx.org/licenses/) is the list of all the SPDX licenses that would work to test for now. @ithompson4

**Comment by techytushar** [comment]
@ithompson4 is it working fine now? Which version of Python are running it on?

**Comment by ithompson4** [comment]
Hello @techytushar. I have Python 3.6.5. 
I checked a couple days ago and it did not work for me.  I am preparing for my final exams now, will be able to try again next Wednesday.

**Comment by techytushar** [comment]
The spdx-online-tools is not compatible with Python3, try with Python2.x and it should run fine.

**Comment by ithompson4** [comment]
Ok, I will with try  Python2.x 
But in the [Requirements section](https://github.com/spdx/spdx-online-tools#requirements-windows), it says "Install some version of Python (2.7 or higher)".

**Comment by ithompson4** [comment]
Hello @techytushar. I installed Python 2.7.16 from Anaconda. While running the command `python manage.py migrate`, I get this error:

`(venv) (base) C:\>python C:/Users/Irina/Documents/Git_Spdx/spdx-online-tools/src/manage.py migrate
ImportError: No module named _multiarray_umath
Traceback (most recent call last):
  File "C:/Users/Irina/Documents/Git_Spdx/spdx-online-tools/src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\__init__.py", line 364, in execute_from_command_line
    utility.execute()
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\__init__.py", line 356, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\base.py", line 283, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\base.py", line 327, in execute
    self.check()
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\base.py", line 359, in check
    include_deployment_checks=include_deployment_checks,
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\commands\migrate.py", line 62, in _run_checks
    issues.extend(super(Command, self)._run_checks(**kwargs))
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\management\base.py", line 346, in _run_checks
    return checks.run_checks(**kwargs)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\checks\registry.py", line 81, in run_checks
    new_errors = check(app_configs=app_configs)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\checks\urls.py", line 16, in check_url_config
    return check_resolver(resolver)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\core\checks\urls.py", line 26, in check_resolver
    return check_method()
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\urls\resolvers.py", line 256, in check
    for pattern in self.url_patterns:
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\urls\resolvers.py", line 407, in url_patterns
    patterns = getattr(self.urlconf_module, "urlpatterns", self.urlconf_module)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\utils\functional.py", line 35, in __get__
    res = instance.__dict__[self.name] = self.func(instance)
  File "C:\Users\Irina\Envs\venv\lib\site-packages\django\urls\resolvers.py", line 400, in urlconf_module
    return import_module(self.urlconf_name)
  File "c:\programdata\anaconda2\Lib\importlib\__init__.py", line 37, in import_module
    __import__(name)
  File "C:\Users\Irina\Documents\Git_Spdx\spdx-online-tools\src\src\urls.py", line 35, in <module>
    from api import views
  File "C:\Users\Irina\Documents\Git_Spdx\spdx-online-tools\src\api\views.py", line 28, in <module>
    import jpype
  File "C:\Users\Irina\Envs\venv\lib\site-packages\jpype\__init__.py", line 17, in <module>
    from ._jpackage import *
  File "C:\Users\Irina\Envs\venv\lib\site-packages\jpype\_jpackage.py", line 18, in <module>
    import _jpype
ImportError: numpy.core.multiarray failed to import`

Please advise. Thank you.

**Comment by techytushar** [comment]
Its quite hard to read this way can you please paste a screenshot. But I would suggest you to use only Python and not Anaconda, then create a virtual environment, install the requirements and then try again.

**Comment by jlovejoy** [comment]
given we have now removed the field for the Standard License Header, I think we can close this issue.
