### ISSUE TITLE
Unit test failure - test_post_submit

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#202]
The following test_post_submit unit test fails on the master branch:

```
======================================================================
FAIL: test_post_submit (app.tests.SubmitNewLicenseViewsTestCase)
POST Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/runner/work/spdx-online-tools/spdx-online-tools/src/app/tests.py", line 1229, in test_post_submit
    self.assertEqual(resp.status_code,200)
AssertionError: 500 != 200
```

**Comment by Ugtan** [comment]
@goneall I'm getting a different error in my machine.

![image](https://user-images.githubusercontent.com/32966387/87609880-63c62680-c721-11ea-9147-b92f125c005e.png)

FYI, All the test cases that are failing are the once that were skipped because they require github credentials which is why these tests were not tested. I will take a look at it.

**Comment by goneall** [comment]
> FYI, All the test cases that are failing are the once that were skipped because they require github credentials which is why these tests were not tested. I will take a look at it.

I added the credentials to Git a couple weeks back - this may have exposed an issue that was introduced some time ago.  The errors are coming from the automated Git actions on checkin.

@Ugtan Thanks for looking into the issue.

**Comment by SidharajYadav** [comment]
How i can contribute
please guide me
I like to solve this problem

**Comment by BanulaKumarage** [comment]
Hi @goneall can you clarify the difference between test_post_submit and test_submit_new_license

**Comment by goneall** [comment]
@BanulaKumarage Probably a better question for @rtgdk - I'm not as familiar with the unit test code

**Comment by BanulaKumarage** [comment]
Hi @goneall I made a pr to fix this issue. Can you review it?

**Comment by rtgdk** [comment]
@BanulaKumarage `test_submit_new_license` is the test for get request on submit-new-license page while `test_post_submit` tests the post request. Both of them have different functionalities
- get -> retrivies page and check the form is displayed with correct values
- post -> checks with correct data license is submitted successfully

**Comment by BanulaKumarage** [comment]
Thank you @rtgdk. I got the idea

**Comment by jlovejoy** [comment]
@rtgdk - what is the status of this?

**Comment by bact** [comment]
This test is currently skipped when there is not GitHub credentials provided.

https://github.com/spdx/spdx-online-tools/blob/a38a0534f7534679906943566e811c316216053d/src/app/tests.py#L1343-L1345

**Comment by bact** [comment]
Confirmed that `test_post_submit` still failed.

Running this command locally and still got error message:

```shell
ACCESS_TOKEN=ghp_... \
TEST_GITHUB_USER_ID=12345 \
TEST_GITHUB_USER_NAME=username \
python src/manage.py test app.tests.SubmitNewLicenseViewsTestCase.test_post_submit
```

Error:

```text
======================================================================
ERROR: test_post_submit (app.tests.SubmitNewLicenseViewsTestCase)
POST Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/art/projects/spdx-online-tools/src/app/tests.py", line 1393, in test_post_submit
    self.assertEqual(licenseRequest.licenseAuthorName, "")
AttributeError: 'NoneType' object has no attribute 'licenseAuthorName'

----------------------------------------------------------------------
```

Similar error to https://github.com/spdx/spdx-online-tools/issues/202#issuecomment-659070291

**Comment by bact** [comment]
PR #681 will fix this
