### ISSUE TITLE
Error when submitting close item

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#223]
The following error occurred in the sandbox instance when submitting a close matching license and selecting that the licenses should match:

```
Error!
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 1537, in issue diffUrl = request.POST['diffUrl'] File "/usr/local/lib/python2.7/site-packages/django/utils/datastructures.py", line 85, in __getitem__ raise MultiValueDictKeyError(repr(key)) MultiValueDictKeyError: "u'diffUrl'"
```

**Comment by goneall** [comment]
Turned out to be a browser caching issue
