### ISSUE TITLE
Unit test failure - api.tests.ConvertFileUploadTests converting XLS spreadsheet

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#282]
The following is the output from the unit tests.  This seems to have been failing since the last 2 upgrades of the SPDX Tools jar file.

```
.....11:40:19.804 [Thread-4] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - I/O error reading SPDX Spreadsheet
java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:258) ~[tool.jar:?]
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:221) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpdxSpreadsheet.<init>(SpdxSpreadsheet.java:107) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpreadsheetStore.deSerialize(SpreadsheetStore.java:329) ~[tool.jar:?]
        at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:148) ~[tool.jar:?]
F11:40:19.881 [Thread-5] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - I/O error reading SPDX Spreadsheet
java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:258) ~[tool.jar:?]
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:221) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpdxSpreadsheet.<init>(SpdxSpreadsheet.java:107) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpreadsheetStore.deSerialize(SpreadsheetStore.java:329) ~[tool.jar:?]
        at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:148) ~[tool.jar:?]
F
======================================================================
FAIL: test_convert_xlsxtordf_api (api.tests.ConvertFileUploadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gary\git\spdx-online-tools\src\api\tests.py", line 178, in test_convert_xlsxtordf_api
    self.assertTrue(resp.status_code==406 or resp.status_code == 201)
AssertionError: False is not true

======================================================================
FAIL: test_convert_xlsxtotag_api (api.tests.ConvertFileUploadTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gary\git\spdx-online-tools\src\api\tests.py", line 186, in test_convert_xlsxtotag_api
    self.assertTrue(resp.status_code==406 or resp.status_code == 201)
AssertionError: False is not true

----------------------------------------------------------------------
```

**Comment by goneall** [comment]
I did a little debugging on this and it doesn't matter if you change the file type from XLS to XLSX.  The files in the example folder verify OK.

**Comment by rtgdk** [comment]
From UI, it works fine. On debugging I found that the real issue is #287. I'll start on this fix.

**Comment by SidharajYadav** [comment]
How i can contribute
please guide me
I like to solve this problem

**Comment by rtgdk** [comment]
@SidharajYadav Setup the repo and try to run the test via `python manage.py test`. Check the failures of these tests and try to work on them backwards from where they are failing and why. 
You can find the tests in `src/app/tests.py` and `src/api/tests.py`

**Comment by BassCoder2808** [comment]
Hi @rtgdk , these tests are passing now I have attached the screenshot for the same. 
![image](https://user-images.githubusercontent.com/65075935/229428109-9096a15c-75ee-412d-b34f-b0a5f2e78451.png)

**Comment by BassCoder2808** [comment]
But for that I needed to remove the `CheckLicenseFileUpload` model as it was not required for `ConvertFileUploadTests` but is required for `CompareFileUpload`. I further found out that `CheckLicenseFileUpload` model does not exist in the `models.py` file. This functionality also needs to be changed. I will create a PR to fix this and will let you know once done
![image](https://user-images.githubusercontent.com/65075935/229428721-c695b22e-0a7f-4bcb-8f4e-8cf512b8c9a4.png)

**Comment by BassCoder2808** [comment]
Hi @goneall @rtgdk, I have created the pull request which will fix the above, please let me know if anything else needs to be added in it
