### ISSUE TITLE
JPype error occurs in production

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#285]
The following error seems to occur after production has been running for some time.  Restarting the instance seems to resolve the issue.  Log files from the production instance attached.  Could not find anything related to this error.

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred:
Traceback (most recent call last):
File "/spdx/src/app/views.py", line 127, in submitNewLicense
  matchingIds, matchingType = utils.check_spdx_license(licenseText)
File "/spdx/src/app/utils.py", line 533, in check_spdx_license
  listedLicense = getListedLicense(licenseID)
File "/spdx/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 88, in getListedLicense
  listed_license = licenseinfofactoryclass.getListedLicenseById(licenseId)
File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 62, in __call__
  raise TypeError
[prod-logs-20-1-2021.zip](https://github.com/spdx/spdx-online-tools/files/5844753/prod-logs-20-1-2021.zip)
("Package {0} is not Callable".format(self.__name))
TypeError: Package org.spdx.rdfparser.license.LicenseInfoFactory.getListedLicenseById is not Callable 
```

**Comment by goneall** [comment]
Second attempt at attaching the logs.
[prod-logs-20-1-2021.zip](https://github.com/spdx/spdx-online-tools/files/5844760/prod-logs-20-1-2021.zip)

**Comment by PhilippWendler** [comment]
I just got the same error on https://tools.spdx.org/app/check_license/:
```
Traceback (most recent call last):
  File "/spdx/src/app/views.py", line 981, in check_license
    matchingId,matchingType = utils.check_spdx_license(licensetext)
  File "/spdx/src/app/utils.py", line 531, in check_spdx_license
    listedLicense = getListedLicense(licenseID)
  File "/spdx/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 88, in getListedLicense
    listed_license = licenseinfofactoryclass.getListedLicenseById(licenseId)
  File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 62, in __call__
    raise TypeError("Package {0} is not Callable".format(self.__name))
TypeError: Package org.spdx.rdfparser.license.LicenseInfoFactory.getListedLicenseById is not Callable
```

**Comment by goneall** [comment]
I just restarted the instance which should resolve this issue for now - please add a comment to this issue if it reoccurs

**Comment by goneall** [comment]
We have a major upgrade planned for this summer which may help resolve this issue long term - until then, just keep adding to this issue if you run into this problem and I'll restart the instance

**Comment by alandtse** [comment]
FYI, just ran into this issue today on check_license.

**Comment by goneall** [comment]
@alandtse I just restarted the server - it should now be working.

**Comment by goneall** [comment]
I haven't seen this error since upgrading the AWS EC2 instance.  Closing this issue.  If it happens again, please open a new issue.
