### ISSUE TITLE
Migration files appear to be stale for Python 3 branch

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#339]
When running manage.py migrate on the python3 branch, I recieve an error indicating the .pyc files are stale:

```
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "c:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1064, in get_code
  File "<frozen importlib._bootstrap_external>", line 513, in _classify_pyc
ImportError: bad magic number in 'api.migrations.0002_submitlicensemodel': b'\x03\xf3\r\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\commands\migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 53, in __init__
    self.build_graph()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 214, in build_graph
    self.load_disk()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 119, in load_disk
    raise ImportError(
ImportError: Couldn't import 'api.migrations.0002_submitlicensemodel' as it appears to be a stale .pyc file.

(venv) C:\Users\gary\git\spdx-online-tools>python src/manage.py migrate
Traceback (most recent call last):
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 116, in load_disk
    migration_module = import_module(migration_path)
  File "c:\Python38\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 975, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 779, in exec_module
  File "<frozen importlib._bootstrap_external>", line 1064, in get_code
  File "<frozen importlib._bootstrap_external>", line 513, in _classify_pyc
ImportError: bad magic number in 'api.migrations.0002_submitlicensemodel': b'\x03\xf3\r\n'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "src/manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 419, in execute_from_command_line
    utility.execute()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\__init__.py", line 413, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 354, in run_from_argv
    self.execute(*args, **cmd_options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 398, in execute
    output = self.handle(*args, **options)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\base.py", line 89, in wrapped
    res = handle_func(*args, **kwargs)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\core\management\commands\migrate.py", line 92, in handle
    executor = MigrationExecutor(connection, self.migration_progress_callback)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\executor.py", line 18, in __init__
    self.loader = MigrationLoader(self.connection)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 53, in __init__
    self.build_graph()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 214, in build_graph
    self.load_disk()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\django\db\migrations\loader.py", line 119, in load_disk
    raise ImportError(
ImportError: Couldn't import 'api.migrations.0002_submitlicensemodel' as it appears to be a stale .pyc file.
```

**Comment by goneall** [comment]
This was caused by stale .pyc files in my migrate directory - once they were deleted, everything worked fine.  Closing the issue.
