### ISSUE TITLE
Python3 Unit Test Error test_tree_editor_text

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#342]
The following unit test error occured on the Python 3 branch:

```
======================================================================
ERROR: test_tree_editor_text (app.tests.LicenseXMLEditorTestCase)
Test for adding, editing and deleting text inside tags using tree editor
----------------------------------------------------------------------
Traceback (most recent call last):
  File "C:\Users\gary\git\spdx-online-tools\src\app\tests.py", line 856, in test_tree_editor_text
    finalXML += i.text.strip()
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 76, in text
    return self._execute(Command.GET_ELEMENT_TEXT)['value']
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\selenium\webdriver\remote\webelement.py", line 633, in _execute
    return self._parent.execute(command, params)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\selenium\webdriver\remote\webdriver.py", line 321, in execute
    self.error_handler.check_response(response)
  File "C:\Users\gary\git\spdx-online-tools\venv\lib\site-packages\selenium\webdriver\remote\errorhandler.py", line 242, in check_response
    raise exception_class(message, screen, stacktrace)
selenium.common.exceptions.StaleElementReferenceException: Message: The element reference of <pre class=" CodeMirror-line "> is stale; either the element is no longer attached to the DOM, it is not in the current frame context, or the document has been refreshed
```

**Comment by BassCoder2808** [comment]
Hi @goneall, does this issue still persists or it has been solved?
If not, I would be happy to contribute to this

**Comment by goneall** [comment]
@BassCoder2808 I don't recall this being fixed - although there have been a few changes to the unit tests since this issue was opened.  If you could run the unit tests locally and see if this error occurs, we can either close this as resolved or fix.  Thanks.

**Comment by BanulaKumarage** [comment]
Hi @goneall. I ran the test in my local machine and the test is passed.  I think the issue has been fixed now.

![image](https://user-images.githubusercontent.com/63106638/224156883-af4e8ada-8595-4fc1-81ad-5bf4d600a15c.png)

**Comment by goneall** [comment]
Hi @BanulaKumarage - Thanks for checking - I'll go ahead and close this issue.
