### ISSUE TITLE
Checking a license with a close match generates error

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#354]
When running check license with a close match (e.g. just delete a couple words from an SPDX license text), the following error occurs:

```
Traceback (most recent call last): File "/spdxonlinetools/src/app/core.py", line 306, in license_check_helper matchingId, matchingType = utils.check_spdx_license(licensetext) File "/spdxonlinetools/src/app/utils.py", line 531, in check_spdx_license listedLicense = getListedLicense(licenseID) File "/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 84, in getListedLicense licenseinfofactoryclass = package.LicenseInfoFactory AttributeError: Java package 'org.spdx.rdfparser.license' is not valid
```

**Comment by goneall** [comment]
Resolved with PR #357
