### ISSUE TITLE
Bug in the https://tools.spdx.org/app/check_license/ error notification

### ISSUE THREAD

**Issue by maryhardy** [spdx/spdx-online-tools#368]
If I enter text with any difference from the license text, I get the following error message, pasted below. I didn't undertand at first that it does this unless the text matches perfectly. A better error message would help clarify that. A more flexible tool like SPDX License Diff https://chrome.google.com/webstore/detail/spdx-license-diff/kfoadicmilbgnicoldjmccpaicejacdh would be even better.
 
Chrome and Microsoft Edge, 2 users, various license text attempts results in the same error message:
 
Traceback (most recent call last): File "/spdx/src/app/views.py", line 981, in check_license matchingId,matchingType = utils.check_spdx_license(licensetext) File "/spdx/src/app/utils.py", line 531, in check_spdx_license listedLicense = getListedLicense(licenseID) File "/spdx/src/spdx-license-matcher/spdx_license_matcher/utils.py", line 88, in getListedLicense listed_license = licenseinfofactoryclass.getListedLicenseById(licenseId) File "/usr/local/lib/python2.7/site-packages/jpype/_jpackage.py", line 62, in __call__ raise TypeError("Package {0} is not Callable".format(self.__name)) TypeError: Package org.spdx.rdfparser.license.LicenseInfoFactory.getListedLicenseById is not Callable

**Comment by goneall** [comment]
@maryhardy Thanks for reporting the issue.

I just tried to duplicate this and I did not get the error.

Can you provide the text you were using to compare when getting the error?

**Comment by goneall** [comment]
@rtgdk From the stack trace it looks like we my still be having a problem with the Java bridge.  Let me know if you have any thoughts.

**Comment by maryhardy** [comment]
Thanks very much for checking on this. I am not able to recreate it now, and I'm not sure why. If you want to close this issue, I can revisit it in the future if I see it again.

**Comment by goneall** [comment]
Thanks for checking @maryhardy - we've had similar problems in the past with one of the libraries we are using in the application.  Please do open an issue if you see it again.
