### ISSUE TITLE
Production system unavailable

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#382]
The production online tools was unavailable on 25 July 2022.

The system is back up through a restart of the AWS EC2 instance and restarting the docker image.

The original cause of the downtime is under investigation.

**Comment by goneall** [comment]
The following error was found in the std-err container logs - not sure if this is related to the downtime:

```

Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
Traceback (most recent call last):
  File "/spdx/src/app/formatxml.py", line 253, in <module>
    process(fname)
  File "/spdx/src/app/formatxml.py", line 101, in process
    ser = fmt(blocks)
  File "/spdx/src/app/formatxml.py", line 166, in fmt
    indent = l * config['lvl_indent']
UnboundLocalError: local variable 'l' referenced before assignment
```

**Comment by goneall** [comment]
The following errors were in the std-out for the Docker image - likely unrelated to the downtime:

```
08:04:13.379 [Thread-65] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 687 column 75): {E211} Base URI is null, but there are relative URIs to resolve.: <LicenseRef-BSD-3-Clause-UC>
08:04:13.380 [Thread-65] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 706 column 67): {E211} Base URI is null, but there are relative URIs to resolve.: <LicenseRef-GPL-2.0>
08:04:13.380 [Thread-65] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 713 column 68): {E211} Base URI is null, but there are relative URIs to resolve.: <LicenseRef-LGPL-2.0>
08:04:13.380 [Thread-65] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 720 column 65): {E211} Base URI is null, but there are relative URIs to resolve.: <LicenseRef-Xming>
08:04:13.417 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file7b3eac4e7def3b3bffa60a3870b50034.
08:04:13.417 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property licenseConcluded ID SPDXRef-file7b3eac4e7def3b3bffa60a3870b50034.
08:04:13.419 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file7b3eac4e7def3b3bffa60a3870b50034.
08:04:13.419 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file7b3eac4e7def3b3bffa60a3870b50034.
08:04:13.425 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-filef1c730a52fed8182847b459c8a7cccef.
08:04:13.426 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property licenseConcluded ID SPDXRef-filef1c730a52fed8182847b459c8a7cccef.
08:04:13.427 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-filef1c730a52fed8182847b459c8a7cccef.
08:04:13.427 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-filef1c730a52fed8182847b459c8a7cccef.
08:04:13.434 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file215ba888327b0e6333d6419b8de60e8e.
08:04:13.435 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property licenseConcluded ID SPDXRef-file215ba888327b0e6333d6419b8de60e8e.
08:04:13.435 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property copyrightText ID SPDXRef-file215ba888327b0e6333d6419b8de60e8e.
08:04:13.436 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file215ba888327b0e6333d6419b8de60e8e.
08:04:13.437 [Thread-65] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - Error getting single value.  Multiple values for property fileName ID SPDXRef-file215ba888327b0e6333d6419b8de60e8e.
08:51:30.225 [Thread-17] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - I/O error reading SPDX Spreadsheet
java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:258) ~[tool.jar:?]
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:221) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpdxSpreadsheet.<init>(SpdxSpreadsheet.java:107) [tool.jar:?]
        at org.spdx.spreadsheetstore.SpreadsheetStore.deSerialize(SpreadsheetStore.java:339) [tool.jar:?]
        at org.spdx.tools.Verify.verify(Verify.java:126) [tool.jar:?]
12:59:08.482 [Thread-90] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - Spreadsheet version SPDX-2.2 not supported.
13:46:35.869 [Thread-12] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - Spreadsheet version SPDX-2.2 not supported.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
16:22:37.898 [main] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 6073 column 73): {E211} Base URI is null, but there are relative URIs to resolve.: <SPDX Document created by ScanCode Toolkit>
16:22:38.145 [main] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 14751 column 50): {E211} Base URI is null, but there are relative URIs to resolve.: <SPDXRef-001>
16:22:38.788 [main] ERROR org.spdx.spdxRdfStore.SpdxOwlOntology - http://spdx.org/rdf/terms#licenseName is not an SPDX property
19:06:55.343 [Thread-67] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 2 column 11): Open quote is expected for attribute "xmlns:rdf" associated with an  element type  "rdf:RDF".
Verification errors were found in /spdx/src/app/media/AnonymousUser/1657706197/talko.spdx.  See verification errors sheet for details.
Verification errors were found in /spdx/src/app/media/AnonymousUser/1657706197/talko-premium.spdx.  See verification errors sheet for details.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
18:05:52.251 [Thread-25] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 1 column 1): Content is not allowed in prolog.
18:07:02.015 [Thread-9] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 1 column 1): Content is not allowed in prolog.
23:41:16.876 [Thread-29] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - Required cell Package Download Location missing for row 1 in PackageInfo sheet.
04:19:22.626 [Thread-76] ERROR org.spdx.spreadsheetstore.SpdxSpreadsheet - I/O error reading SPDX Spreadsheet
java.io.IOException: Your InputStream was neither an OLE2 stream, nor an OOXML stream
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:258) ~[tool.jar:?]
        at org.apache.poi.ss.usermodel.WorkbookFactory.create(WorkbookFactory.java:221) ~[tool.jar:?]
        at org.spdx.spreadsheetstore.SpdxSpreadsheet.<init>(SpdxSpreadsheet.java:107) [tool.jar:?]
        at org.spdx.spreadsheetstore.SpreadsheetStore.deSerialize(SpreadsheetStore.java:339) [tool.jar:?]
        at org.spdx.tools.SpdxConverter.convert(SpdxConverter.java:151) [tool.jar:?]
04:20:21.294 [Thread-32] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 1 column 1): Content is not allowed in prolog.
WARNING: sun.reflect.Reflection.getCallerClass is not supported. This will impact performance.
11:15:29.693 [Thread-1] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 1 column 1): Content is not allowed in prolog.
11:41:10.685 [Thread-157] ERROR org.spdx.spdxRdfStore.RdfSpdxDocumentModelManager - ID  does not exist in the model.
21:37:21.917 [Thread-39] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-@vue/babel-sugar-v-model.  Must be an SPDX Identifier or Anonymous
21:40:25.111 [Thread-41] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-vue/babel-sugar-functional-vue.  Must be an SPDX Identifier or Anonymous
21:42:22.244 [Thread-42] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-vue/babel-sugar-functional-vue.  Must be an SPDX Identifier or Anonymous
21:43:04.784 [Thread-43] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-types/q.  Must be an SPDX Identifier or Anonymous
21:44:09.224 [Thread-44] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-types/q.  Must be an SPDX Identifier or Anonymous
21:44:49.699 [Thread-45] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-ttskch/select2-bootstrap4-theme.  Must be an SPDX Identifier or Anonymous
21:45:23.496 [Thread-46] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-soda/get-current-script.  Must be an SPDX Identifier or Anonymous
21:45:49.099 [Thread-47] ERROR org.spdx.jacksonstore.JacksonSerializer - Invalid ID SPDXRef-sweetalert2/theme-bootstrap-4.  Must be an SPDX Identifier or Anonymous
XML Parse Error: syntax error: line 1, column 0
XML Parse Error: syntax error: line 1, column 0
XML Parse Error: no element found: line 1, column 38
XML Parse Error: undefined entity &xxe;: line 4, column 51
XML Parse Error: undefined entity &xxe;: line 4, column 51
14:40:31.235 [Thread-164] ERROR org.apache.jena.rdf.model.impl.RDFDefaultErrorHandler - (line 1 column 1): Content is not allowed in prolog.
```

**Comment by goneall** [comment]
I found this in the syslog:

```
Jul 25 17:16:34 ip-172-31-6-122 systemd[1]: Started Unattended Upgrades Shutdown.
```

And several networking related messages:

```

Jul 25 17:16:37 ip-172-31-6-122 systemd-timesyncd[593]: Network configuration ch
anged, trying to establish connection.
Jul 25 17:16:37 ip-172-31-6-122 systemd-udevd[1344]: link_config: autonegotiatio
n is unset or enabled, the speed and duplex are not writable.
Jul 25 17:16:37 ip-172-31-6-122 systemd-udevd[1344]: Could not generate persiste
nt MAC address for veth3d8a564: No such file or directory
Jul 25 17:16:37 ip-172-31-6-122 systemd-udevd[1352]: link_config: autonegotiatio
n is unset or enabled, the speed and duplex are not writable.
Jul 25 17:16:37 ip-172-31-6-122 systemd-udevd[1352]: Could not generate persiste
nt MAC address for veth309a3b7: No such file or directory
Jul 25 17:16:37 ip-172-31-6-122 systemd-timesyncd[593]: Network configuration ch
anged, trying to establish connection.
Jul 25 17:16:37 ip-172-31-6-122 systemd-timesyncd[593]: Network configuration ch
anged, trying to establish connection.

```

Not sure if it is related

**Comment by goneall** [comment]
More evidence of network errors from syslog:
```
Jul 25 06:35:14 ip-172-31-6-122 snapd[9129]: autorefresh.go:528: Cannot prepare
auto-refresh change due to a permanent network error: persistent network error:
Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.i
o: Temporary failure in name resolution
Jul 25 06:35:14 ip-172-31-6-122 snapd[9129]: stateengine.go:149: state ensure er
ror: persistent network error: Post https://api.snapcraft.io/v2/snaps/refresh: d
ial tcp: lookup api.snapcraft.io: Temporary failure in name resolution
Jul 25 07:00:14 ip-172-31-6-122 snapd[9129]: autorefresh.go:528: Cannot prepare
auto-refresh change due to a permanent network error: persistent network error:
Post https://api.snapcraft.io/v2/snaps/refresh: dial tcp: lookup api.snapcraft.i
o: Temporary failure in name resolution
Jul 25 07:00:14 ip-172-31-6-122 snapd[9129]: stateengine.go:149: state ensure er
ror: persistent network error: Post https://api.snapcraft.io/v2/snaps/refresh: d
ial tcp: lookup api.snapcraft.io: Temporary failure in name resolution
```

**Comment by rtgdk** [comment]
From the code, looks like `UnboundLocalError: local variable 'l' referenced before assignment` can happen if `m.group('level')` is false

```
def fmt(blocks):
    bregexp = re.compile(r'((?P<level>\d+)#)?(?P<paragraph>.*)')
    ser = ''
    for line in blocks.split('\n'):
        if line == '':
            continue
        m = bregexp.match(line)
        if m.group('level'):
            l = int(m.group('level'))
        else:
            logger.error('Block without level: "{}"'.format(line))
        par = m.group('paragraph')
        if par == '':
            continue
        indent = l * config['lvl_indent']
        width = config['max_width'] - indent
        for fmtline in to_lines(par, width):
            ser += indent * ' ' + fmtline + '\n'
    return ser

**Comment by OliverFendt** [comment]
Hi Gary,

thank you for providing the online service of the SPDX tools. This is really great. However I am currently no able to access them anymore. I am using as URL https://tools.spdx.org/ but I always get "ERR_TIMED_OUT". Do I have the wrong URL?

Another question: I recently tried to validate a mid sized SPDX Tag-Value file (11.2 MB) and always got the error cannot connect to the system - is there a limitation in size for validation?

**Comment by goneall** [comment]
Thanks @OliverFendt for reporting the error.  I just checked and the server itself is down.  I'm rebooting it now.  Later tonight I'll see if I can find a cause for the outage.

**Comment by goneall** [comment]
@OliverFendt This server is back up

**Comment by OliverFendt** [comment]
@goneall yes, it is working again. Thank you very much for taking care

**Comment by goneall** [comment]
I took a look at the system logs and didn't see any clues as to why the server was down.

I added an alert to send me an email if this situation happens again.

**Comment by goneall** [comment]
Closing this issue as it hasn't happened in a while
