### ISSUE TITLE
Errors submitting license when a close diff is found

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#411]
The following response was sent when submitting a new license with [this text](https://raw.githubusercontent.com/viennacl/viennacl-dev/master/LICENSE):

`Unexpected error while posting to github, please e…turned 401 status code - message Bad credentials\n`

**Comment by goneall** [comment]
Below is the full text of the error:

```
Unexpected error while posting to github, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last):
  File "/spdx/src/app/views.py", line 1477, in post_to_github
    raise Exception("Post to Github returned {0} status code - message {1}".format(statusCode, jsonResponse["message"]))
Exception: Post to Github returned 401 status code - message Bad credentials
```

**Comment by goneall** [comment]
I recreated the authentication token which fixed this issue, but I now ran into the following error:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/spdx/src/app/views.py", line 1174, in issue submissionDatetime=now, userEmail=userEmail, notes=licenseNotes, xml=xml) NameError: name 'userEmail' is not defined
```

Email was removed from the model during the recent updates to the license submittal form which caused this issue.
