### ISSUE TITLE
SQL Error testing the latest codebase

### ISSUE THREAD

**Issue by goneall** [spdx/spdx-online-tools#485]
Got the following error when testing a license submit:

```
Unexpected error, please email the SPDX technical workgroup that the following error has occurred: Traceback (most recent call last): File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute return Database.Cursor.execute(self, query, params) sqlite3.IntegrityError: NOT NULL constraint failed: app_licenserequest.issueId The above exception was the direct cause of the following exception: Traceback (most recent call last): File "/spdxonlinetools/src/app/views.py", line 1169, in issue licenseRequest.save() File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 739, in save self.save_base(using=using, force_insert=force_insert, File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 776, in save_base updated = self._save_table( File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 881, in _save_table results = self._do_insert(cls._base_manager, using, fields, returning_fields, raw) File "/usr/local/lib/python3.10/site-packages/django/db/models/base.py", line 919, in _do_insert return manager._insert( File "/usr/local/lib/python3.10/site-packages/django/db/models/manager.py", line 85, in manager_method return getattr(self.get_queryset(), name)(*args, **kwargs) File "/usr/local/lib/python3.10/site-packages/django/db/models/query.py", line 1270, in _insert return query.get_compiler(using=using).execute_sql(returning_fields) File "/usr/local/lib/python3.10/site-packages/django/db/models/sql/compiler.py", line 1416, in execute_sql cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 98, in execute return super().execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 66, in execute return self._execute_with_wrappers(sql, params, many=False, executor=self._execute) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 75, in _execute_with_wrappers return executor(sql, params, many, context) File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 79, in _execute with self.db.wrap_database_errors: File "/usr/local/lib/python3.10/site-packages/django/db/utils.py", line 90, in __exit__ raise dj_exc_value.with_traceback(traceback) from exc_value File "/usr/local/lib/python3.10/site-packages/django/db/backends/utils.py", line 84, in _execute return self.cursor.execute(sql, params) File "/usr/local/lib/python3.10/site-packages/django/db/backends/sqlite3/base.py", line 423, in execute return Database.Cursor.execute(self, query, params) django.db.utils.IntegrityError: NOT NULL constraint failed: app_licenserequest.issueId
 Ok
Submit a New License to the SPDX License List

Please review the [SPDX License List inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md) before submitting a new license. Once you have submitted a license, please follow the [issue in Github](https://github.com/spdx/license-list-XML/issues) and be prepared to help create the required XML and test text files if the license is accepted for submission.
Briefly explain how this license
meets the [license inclusion principles](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-inclusion-principles.md)
Full name or title of license
Suggest short identifier
(See [Fields, section B](https://github.com/spdx/license-list-XML/blob/main/DOCS/license-fields.md) for more details)
URL to license text
+ Add a source
OSI Status
-
Text of license
License author or steward?
(If not known, put 'Unknown')
Unknown
URL to project(s) that use license
+ Add an example project URL
```

**Comment by goneall** [comment]
This is probably caused by migrating the SQL database for PR #456 then reverting the changes

**Comment by goneall** [comment]
Confirmed this is due to the upgrade and revert - closing this issue
