### ISSUE TITLE
Tests failing. CI missing

### ISSUE THREAD

**Issue by nezhar** [spdx/spdx-online-tools#63]
There are certain test cases that break currently. It would be great to add Travis CI or something similar to test each new commit.

Would it make sense to add a code style check? I can recommend [pycodestyle](https://pypi.org/project/pycodestyle/)

```
======================================================================
ERROR: test_generate_xml (app.tests.SubmitNewLicenseViewsTestCase)
View for generating an xml from license submittal form fields
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nezhar/DEV/PYTHON/spdx-online-tools/src/app/tests.py", line 985, in test_generate_xml
    xml = generateLicenseXml(self.osiApproved, self.shortIdentifier, self.fullname, self.urls,
NameError: global name 'generateLicenseXml' is not defined

======================================================================
FAIL: test_license_requests (app.tests.LicenseRequestsViewsTestCase)
GET Request for license requests list
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nezhar/DEV/PYTHON/spdx-online-tools/src/app/tests.py", line 938, in test_license_requests
    self.assertEqual(resp.resolver_match.func.__name__,"license_requests")
AssertionError: 'licenseRequests' != u'license_requests'

======================================================================
FAIL: test_post_submit (app.tests.SubmitNewLicenseViewsTestCase)
POST Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nezhar/DEV/PYTHON/spdx-online-tools/src/app/tests.py", line 980, in test_post_submit
    self.assertNotEqual(resp.redirect_chain,[])
AssertionError: [] == []

======================================================================
FAIL: test_submit_new_license (app.tests.SubmitNewLicenseViewsTestCase)
GET Request for submit a new license
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nezhar/DEV/PYTHON/spdx-online-tools/src/app/tests.py", line 963, in test_submit_new_license
    self.assertEqual(resp.resolver_match.func.__name__,"license_requests")
AssertionError: 'submitNewLicense' != u'license_requests'

======================================================================
FAIL: test_invalid_license_name (app.tests.XMLUploadTestCase)
POST request for xml input using invalid license name
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/home/nezhar/DEV/PYTHON/spdx-online-tools/src/app/tests.py", line 569, in test_invalid_license_name
    self.assertEqual(resp.status_code,404)
AssertionError: 500 != 404

----------------------------------------------------------------------
Ran 63 tests in 42.095s

FAILED (failures=4, errors=1)
Destroying test database for alias 'default'...
```

**Comment by goneall** [comment]
This has been merged and deployed.  Thanks @techytushar !
